
export class Usuario {
    id: number = 0;
    empresaId: number;
    pessoaId: number;
    nomeUsuario: string;
    senha: string;
    biometria: string;
    sessao: string;
    ativo: boolean;
    tipoUsuario: number;
    email: string;

}


// export class Usuario {
//     id: number
//     dtCriacao : Date;
//     nome: string
//     login : string
//     senha : string
//     cracha : string
//     bolSistema:  boolean
//     bolResetaSenha : boolean
//     dataTrocaSenha : Date
//     criadoPor : number
//     bloqueado : boolean
//     empresaid : string
//     grupoUsuarioid : string
//     profissional : boolean
//     agendas : Array<Agenda>
//     grupoUsuario : Array<GrupoUsuario>

// }

// Generated by https://quicktype.io


